# Copyright 2017 Diamond Light Source
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the License.


name: CI - Update README from Template

on:
  push:
    branches:
      - '**'
    paths:
      - README.md
      - README.template
      - .github/workflows/readme.yml

  workflow_dispatch:

env:
  JINJA_CMD: |
    import os, sys, jinja2
    sys.stdout.write(jinja2.Template(sys.stdin.read()).render(env=os.environ))

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2

      - name: Install Jinja2
        run: pip3 install Jinja2

      - name: Add ENV variable for current branch
        run: |
          echo "GITHUB_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Execute Jinja2
        run: |
          cat README.template | python3 -c "${JINJA_CMD}" > README.md

      - name: Commit updated README and push to current branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: README.md
          commit_message: Regenerate README from template
